### ISSUE TITLE
cards level error

### ISSUE THREAD

**Issue by bertux** [NuTyX/extra#1]
After syncing everything listed in README.md the command cards level throws this message :
WARNING phonon from /houaphan/gui-extra/python-qt4 NOT FOUND ...

**Comment by tnut** [comment]
Will try to fix it tonight

2015-10-19 23:27 GMT+02:00 Bertrand Juglas <notifications@github.com>:

**Comment by bertux** [comment]
Thank you, maybe it's because I've not done anything with the KDE
repositories which may contain phonon package.
