### ISSUE TITLE
qemu-static fails

### ISSUE THREAD

**Issue by tnut** [NuTyX/extra#13]
After all set: means

1. sync all base,cli,gui, base-extra, cli-extra,gui-extra
2. configuration set

I try: cards level

WARNING glib-static from /DEPOT/gui-extra/qemu-static NOT FOUND
WARNING pcre-static  /DEPOT/gui-extra/qemu-static  NOT FOUND

When I try to compile qemu-static

/usr/bin/ld: cannot find -lgthread-2.0
/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -lgcrypt
/usr/bin/ld: cannot find -lgpg-error
/usr/bin/ld: cannot find -lgpg-error
collect2: error: ld returned 1 exit status
/tmp/work/src/qemu-2.5.0/rules.mak:123: recipe for target 'tests/qemu-iotests/socket_scm_helper' failed

**Comment by berlius** [comment]
j'ai déjà donné la réponse dans la documentation dès le premier paragraphe voir /houaphan/www/fr/nutyx-arm.html. Donc je me cite "Selon votre configuration, vous pouvez rencontrer le message "impossible de trouver -lpcre ou une autre librairie" lors de la compilation de "qemu-static". C'est parce que vous avez seulement la librairie dynamique sur votre système et pas la statique. Il suffit donc de recompiler cette dernière avec l'option "--enable-static" passée à "configure" puis de relancer la compilation de "qemu"."
j'ai transféré il y a deux jours avec les autres "glib-static" et "pcre-static" qui se trouvent dans /houaphan/cli-arm et j'ai prevenu dans mon message du 5 mars sur le forum. Je me "re-cite" donc "Avant de commencer à compiler bien mettre à jour votre fichier "/etc/cards.conf" afin qu'il prenne en compte les deux nouveaux dossiers créés "/houaphan/base-arm" et "/houaphan/cli-arm"."




    On Sunday, March 6, 2016 12:03 PM, tnut <notifications@github.com> wrote:
 

 After all set: means   
   - sync all base,cli,gui, base-extra, cli-extra,gui-extra
   - configuration set
I try: cards levelWARNING glib-static from /DEPOT/gui-extra/qemu-static NOT FOUND
WARNING pcre-static /DEPOT/gui-extra/qemu-static NOT FOUNDWhen I try to compile qemu-static/usr/bin/ld: cannot find -lgthread-2.0
/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -lgcrypt
/usr/bin/ld: cannot find -lgpg-error
/usr/bin/ld: cannot find -lgpg-error
collect2: error: ld returned 1 exit status
/tmp/work/src/qemu-2.5.0/rules.mak:123: recipe for target 'tests/qemu-iotests/socket_scm_helper' failed—

**Comment by tnut** [comment]
Merci pour  l'info,

Je vais voir ça, et voir comment expliquer tout ça en détail dans la doc

**Comment by tnut** [comment]
libgpg-error tu confirmes qu'il le faut aussi en statique ?

**Comment by tnut** [comment]
même moi j'ai besoin de cette doc. J'oublie tout
