### ISSUE TITLE
Maj kernel-lts pose problème

### ISSUE THREAD

**Issue by Pierre-NuTyX** [NuTyX/extra#27]
check 
- irssi
- kernel-lts
- nvidia 
- virtualbox
- virtualbox-cli

1/
- cards upgrade
- reboot 
- plouf .... uname -a : toujours en kernel 4.4.6

recopie de l'install de secours et on recommence, même check et ... 

2/
- del -a kernel-lts
- rm /boot/*
- rm -rf /lib/modules/4.4.6
- get kernel-lts .... s'affiche 4.4.8...
- ls -l /boot  ... ok
- ls /lib/modules/4.4.8 ... ok
- reboot
- plouf .... uname -a : toujours en kernel 4.4.6

PS : a chaque méthode, l'install de tout ce qui devait être mis à jour par check s'installe automatiquement avant le reboot.

Voili Voilà

**Comment by tnut** [comment]
je penche pour une erreur dans grub.cfg il pointe le kernel d une autre partition

**Comment by Pierre-NuTyX** [comment]
```
menuentry "[1] NuTyX 8.1 sur sda3" {  
  linux /boot/kernel root=/dev/sda3 ro
  initrd /boot/initrd
}
```
```
root [ ~ ]# ls -l /boot/
total 62836
-rw-r--r-- 1 root root 59956469 avril 10 07:59 initrd
lrwxrwxrwx 1 root root       22 avril 10 07:59 kernel -> kernel-4.4.6-NuTyX-lts
-rw-r--r-- 1 root root  4381760 avril 10 07:59 kernel-4.4.6-NuTyX-lts
root [ ~ ]# 
```

**Comment by tnut** [comment]
oui il manque la ligne set root.. relire
http://nutyx.org/fr/grub-install.html

**Comment by tnut** [comment]
Pour info c'est le 4.4.6 que je vois dans /boot

**Comment by Pierre-NuTyX** [comment]
vu, m'avez semblé avoir vu que set root n’était pas utile ... enfin bref, il semble que oui :)

pour le kernel 4.4.6 , c'est normal puisque la maj plantait

**Comment by Pierre-NuTyX** [comment]
ça marche nettement mieux ....

va falloir que je songe à prendre la retraite .... :(

**Comment by tnut** [comment]
merci de fermer l issue si résolu

**Comment by Pierre-NuTyX** [comment]
ben dis donc, ça devient très convivial tout ça ..

**Comment by tnut** [comment]
mega reactivitée
