### ISSUE TITLE
[Mate Desktop] Icones manquantes dans les raccourcis de LibreOffice.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/extra#45]
Un bug graphique assez génant. Je l'ai sous Mate Desktop - à vérifier avec Gnome ou Xfce - mais qunad j'installer LibreOffice, les icones du logiciel (dans le menu Applications / Bureautique) sont absentes :(

Cf la capture d'écran ci-jointe au bug.

![icones manquantes libreoffice](https://cloud.githubusercontent.com/assets/8571419/16782221/d797f104-487e-11e6-9996-1d676ad67a9d.png)

**Comment by tnut** [comment]
Je regarderai

**Comment by FredBezies** [comment]
Les icones s'affichent avec Xfce. J'ai modifié le titre en conséquence.

**Comment by FredBezies** [comment]
J'ai essayé de rajouter le paquet gnome-icon-theme. Sans réussite. Bizarre :(

**Comment by tnut** [comment]
Meme remarque issue que #13 de mate

**Comment by FredBezies** [comment]
Donc, une autre note de publication pour les personnes qui tomberaient sur le bug, ce ne serait pas une mauvaise idée :D

**Comment by tnut** [comment]
je vois pas trop comment je pourrai faire une note de publication et s'assurer qu'elle soie lue

**Comment by FredBezies** [comment]
Euh... Un addenda dans la section pour l'installation de Mate ? Simple idée, hein ;)
