### ISSUE TITLE
Midori : problème d'affichage avec gtk3.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/extra#46]
Midori souffre d'un problème de "thème" avec gtk 3.20.x. Si on le lance, les icones sont entassées les unes sur les autres. Le problème est particulièrement visible dans la barre supérieure de la fenêtre du logiciel.

Cf la capture d'écran ci-dessous.

![midori](https://cloud.githubusercontent.com/assets/8571419/16846216/ce5d54b2-49eb-11e6-997a-0f9b0b5163a4.png)

**Comment by tnut** [comment]
Il faut changer de thème ds xfce4 si je me souviens bien

**Comment by FredBezies** [comment]
Merci pour l'info !

**Comment by tnut** [comment]
Theme issue, cannot fixe it
