### ISSUE TITLE
Chromium + mate : pas d'icone dans le menu Applications / Internet.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/extra#49]
Testé avec NuTyX 8.2rc2. En gros, le même bug que pour le bug 45.

![icone manquante chromium](https://cloud.githubusercontent.com/assets/8571419/18865784/4c3b0848-849d-11e6-90f1-29edf80bc797.png)

**Comment by tnut** [comment]
fixed

**Comment by FredBezies** [comment]
Merci !
