### ISSUE TITLE
Python-qt4 is needed to launch hp-toolbox.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/extra#50]
Simple bug to reproduce. When you install hplip, python-qt4 which is used to power gui tools like hp-toolbox is not installed.

A simple `sudo cards install python-qt4` fixes this bug.

**Comment by FredBezies** [comment]
Could be a great idea to add this depend for NuTyX 8.3, I think :)

**Comment by tnut** [comment]
Meme remarque que l'issue que 13 de mate.

**Comment by FredBezies** [comment]
Au minimum, rajouter une note de publication ? Ça ne mange pas de pain :D

**Comment by tnut** [comment]
Je vois bien l'idée, mais où la mettre ?

**Comment by FredBezies** [comment]
Dans une section consacrée à tout ce qui est gestion des imprimantes dans le wiki ?

Simple suggestion.

Au pire, rajouter le paquet dans les dépendances d'hplip pour être tranquille, même si cela alourdit un brin l'installation.
