### ISSUE TITLE
Problème wifi Configuration wifi Atheros AR242x / AR542x

### ISSUE THREAD

**Issue by nilan14** [NuTyX/extra#51]
Voici le config que j'ai utilisé pour recompiler le noyau et résoudre le problème de wifi de mon netbook.
J'ai changé aussi l'option Processor family.

Nicola

[config.txt](https://github.com/NuTyX/extra/files/527389/config.txt)

**Comment by tnut** [comment]
Merci nilan14

J'ai ajouté tout ce petit monde et quelques autres options. Merci pour tes retours. Il va y avoir un nouveau kernel dispo avec nouvelle iso 8.2.1

**Comment by tnut** [comment]
fixed
